//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfo
    {
        public int ID { get; set; }
        public int IDBill { get; set; }
        public int IDFood { get; set; }
        public int Count { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Food Food { get; set; }
    }
}
